name: build java
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - docker/**
jobs:
  push:
    name: "gravit-eggs:java_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 11
          - 17
          - 21
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - uses: docker/build-push-action@v5
        with:
          context: ./docker
          file: ./docker/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/gravit-core/gravit-eggs:java_${{ matrix.tag }}